using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SMSFinger.DAL
{
    /// <summary>
    /// Controller class for accouts
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class AccoutController
    {
        // Preload our schema..
        Accout thisSchemaLoad = new Accout();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public AccoutCollection FetchAll()
        {
            AccoutCollection coll = new AccoutCollection();
            Query qry = new Query(Accout.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public AccoutCollection FetchByID(object Id)
        {
            AccoutCollection coll = new AccoutCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public AccoutCollection FetchByQuery(Query qry)
        {
            AccoutCollection coll = new AccoutCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (Accout.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (Accout.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Acname,string Mpoc,string Mobileno,string Email,int? Status,DateTime? Datecreated,string Remarks)
	    {
		    Accout item = new Accout();
		    
            item.Acname = Acname;
            
            item.Mpoc = Mpoc;
            
            item.Mobileno = Mobileno;
            
            item.Email = Email;
            
            item.Status = Status;
            
            item.Datecreated = Datecreated;
            
            item.Remarks = Remarks;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string Acname,string Mpoc,string Mobileno,string Email,int? Status,DateTime? Datecreated,string Remarks)
	    {
		    Accout item = new Accout();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Acname = Acname;
				
			item.Mpoc = Mpoc;
				
			item.Mobileno = Mobileno;
				
			item.Email = Email;
				
			item.Status = Status;
				
			item.Datecreated = Datecreated;
				
			item.Remarks = Remarks;
				
	        item.Save(UserName);
	    }
    }
}
