using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SMSFinger.DAL
{
	/// <summary>
	/// Strongly-typed collection for the Accout class.
	/// </summary>
    [Serializable]
	public partial class AccoutCollection : ActiveList<Accout, AccoutCollection>
	{	   
		public AccoutCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>AccoutCollection</returns>
		public AccoutCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                Accout o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the accouts table.
	/// </summary>
	[Serializable]
	public partial class Accout : ActiveRecord<Accout>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public Accout()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public Accout(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public Accout(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public Accout(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("accouts", TableType.Table, DataService.GetInstance("SMSFingerProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarAcname = new TableSchema.TableColumn(schema);
				colvarAcname.ColumnName = "acname";
				colvarAcname.DataType = DbType.String;
				colvarAcname.MaxLength = 100;
				colvarAcname.AutoIncrement = false;
				colvarAcname.IsNullable = true;
				colvarAcname.IsPrimaryKey = false;
				colvarAcname.IsForeignKey = false;
				colvarAcname.IsReadOnly = false;
				colvarAcname.DefaultSetting = @"";
				colvarAcname.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAcname);
				
				TableSchema.TableColumn colvarMpoc = new TableSchema.TableColumn(schema);
				colvarMpoc.ColumnName = "mpoc";
				colvarMpoc.DataType = DbType.String;
				colvarMpoc.MaxLength = 100;
				colvarMpoc.AutoIncrement = false;
				colvarMpoc.IsNullable = true;
				colvarMpoc.IsPrimaryKey = false;
				colvarMpoc.IsForeignKey = false;
				colvarMpoc.IsReadOnly = false;
				colvarMpoc.DefaultSetting = @"";
				colvarMpoc.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMpoc);
				
				TableSchema.TableColumn colvarMobileno = new TableSchema.TableColumn(schema);
				colvarMobileno.ColumnName = "mobileno";
				colvarMobileno.DataType = DbType.String;
				colvarMobileno.MaxLength = 15;
				colvarMobileno.AutoIncrement = false;
				colvarMobileno.IsNullable = true;
				colvarMobileno.IsPrimaryKey = false;
				colvarMobileno.IsForeignKey = false;
				colvarMobileno.IsReadOnly = false;
				colvarMobileno.DefaultSetting = @"";
				colvarMobileno.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMobileno);
				
				TableSchema.TableColumn colvarEmail = new TableSchema.TableColumn(schema);
				colvarEmail.ColumnName = "email";
				colvarEmail.DataType = DbType.String;
				colvarEmail.MaxLength = 100;
				colvarEmail.AutoIncrement = false;
				colvarEmail.IsNullable = true;
				colvarEmail.IsPrimaryKey = false;
				colvarEmail.IsForeignKey = false;
				colvarEmail.IsReadOnly = false;
				colvarEmail.DefaultSetting = @"";
				colvarEmail.ForeignKeyTableName = "";
				schema.Columns.Add(colvarEmail);
				
				TableSchema.TableColumn colvarStatus = new TableSchema.TableColumn(schema);
				colvarStatus.ColumnName = "status";
				colvarStatus.DataType = DbType.Int32;
				colvarStatus.MaxLength = 0;
				colvarStatus.AutoIncrement = false;
				colvarStatus.IsNullable = true;
				colvarStatus.IsPrimaryKey = false;
				colvarStatus.IsForeignKey = false;
				colvarStatus.IsReadOnly = false;
				colvarStatus.DefaultSetting = @"";
				colvarStatus.ForeignKeyTableName = "";
				schema.Columns.Add(colvarStatus);
				
				TableSchema.TableColumn colvarDatecreated = new TableSchema.TableColumn(schema);
				colvarDatecreated.ColumnName = "datecreated";
				colvarDatecreated.DataType = DbType.DateTime;
				colvarDatecreated.MaxLength = 0;
				colvarDatecreated.AutoIncrement = false;
				colvarDatecreated.IsNullable = true;
				colvarDatecreated.IsPrimaryKey = false;
				colvarDatecreated.IsForeignKey = false;
				colvarDatecreated.IsReadOnly = false;
				colvarDatecreated.DefaultSetting = @"";
				colvarDatecreated.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDatecreated);
				
				TableSchema.TableColumn colvarRemarks = new TableSchema.TableColumn(schema);
				colvarRemarks.ColumnName = "remarks";
				colvarRemarks.DataType = DbType.String;
				colvarRemarks.MaxLength = 200;
				colvarRemarks.AutoIncrement = false;
				colvarRemarks.IsNullable = true;
				colvarRemarks.IsPrimaryKey = false;
				colvarRemarks.IsForeignKey = false;
				colvarRemarks.IsReadOnly = false;
				colvarRemarks.DefaultSetting = @"";
				colvarRemarks.ForeignKeyTableName = "";
				schema.Columns.Add(colvarRemarks);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["SMSFingerProvider"].AddSchema("accouts",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("Acname")]
		[Bindable(true)]
		public string Acname 
		{
			get { return GetColumnValue<string>(Columns.Acname); }
			set { SetColumnValue(Columns.Acname, value); }
		}
		  
		[XmlAttribute("Mpoc")]
		[Bindable(true)]
		public string Mpoc 
		{
			get { return GetColumnValue<string>(Columns.Mpoc); }
			set { SetColumnValue(Columns.Mpoc, value); }
		}
		  
		[XmlAttribute("Mobileno")]
		[Bindable(true)]
		public string Mobileno 
		{
			get { return GetColumnValue<string>(Columns.Mobileno); }
			set { SetColumnValue(Columns.Mobileno, value); }
		}
		  
		[XmlAttribute("Email")]
		[Bindable(true)]
		public string Email 
		{
			get { return GetColumnValue<string>(Columns.Email); }
			set { SetColumnValue(Columns.Email, value); }
		}
		  
		[XmlAttribute("Status")]
		[Bindable(true)]
		public int? Status 
		{
			get { return GetColumnValue<int?>(Columns.Status); }
			set { SetColumnValue(Columns.Status, value); }
		}
		  
		[XmlAttribute("Datecreated")]
		[Bindable(true)]
		public DateTime? Datecreated 
		{
			get { return GetColumnValue<DateTime?>(Columns.Datecreated); }
			set { SetColumnValue(Columns.Datecreated, value); }
		}
		  
		[XmlAttribute("Remarks")]
		[Bindable(true)]
		public string Remarks 
		{
			get { return GetColumnValue<string>(Columns.Remarks); }
			set { SetColumnValue(Columns.Remarks, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varAcname,string varMpoc,string varMobileno,string varEmail,int? varStatus,DateTime? varDatecreated,string varRemarks)
		{
			Accout item = new Accout();
			
			item.Acname = varAcname;
			
			item.Mpoc = varMpoc;
			
			item.Mobileno = varMobileno;
			
			item.Email = varEmail;
			
			item.Status = varStatus;
			
			item.Datecreated = varDatecreated;
			
			item.Remarks = varRemarks;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varAcname,string varMpoc,string varMobileno,string varEmail,int? varStatus,DateTime? varDatecreated,string varRemarks)
		{
			Accout item = new Accout();
			
				item.Id = varId;
			
				item.Acname = varAcname;
			
				item.Mpoc = varMpoc;
			
				item.Mobileno = varMobileno;
			
				item.Email = varEmail;
			
				item.Status = varStatus;
			
				item.Datecreated = varDatecreated;
			
				item.Remarks = varRemarks;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn AcnameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn MpocColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn MobilenoColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn EmailColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn StatusColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn DatecreatedColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn RemarksColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string Acname = @"acname";
			 public static string Mpoc = @"mpoc";
			 public static string Mobileno = @"mobileno";
			 public static string Email = @"email";
			 public static string Status = @"status";
			 public static string Datecreated = @"datecreated";
			 public static string Remarks = @"remarks";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
