using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SMSFinger.DAL
{
    /// <summary>
    /// Controller class for contacts
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class ContactController
    {
        // Preload our schema..
        Contact thisSchemaLoad = new Contact();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ContactCollection FetchAll()
        {
            ContactCollection coll = new ContactCollection();
            Query qry = new Query(Contact.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ContactCollection FetchByID(object Contactid)
        {
            ContactCollection coll = new ContactCollection().Where("contactid", Contactid).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public ContactCollection FetchByQuery(Query qry)
        {
            ContactCollection coll = new ContactCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Contactid)
        {
            return (Contact.Delete(Contactid) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Contactid)
        {
            return (Contact.Destroy(Contactid) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Contactname,byte[] Mobileno,int? Acid,int? Groupid,DateTime? Datecreated,int? Usercreated,int? Status)
	    {
		    Contact item = new Contact();
		    
            item.Contactname = Contactname;
            
            item.Mobileno = Mobileno;
            
            item.Acid = Acid;
            
            item.Groupid = Groupid;
            
            item.Datecreated = Datecreated;
            
            item.Usercreated = Usercreated;
            
            item.Status = Status;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Contactid,string Contactname,byte[] Mobileno,int? Acid,int? Groupid,DateTime? Datecreated,int? Usercreated,int? Status)
	    {
		    Contact item = new Contact();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Contactid = Contactid;
				
			item.Contactname = Contactname;
				
			item.Mobileno = Mobileno;
				
			item.Acid = Acid;
				
			item.Groupid = Groupid;
				
			item.Datecreated = Datecreated;
				
			item.Usercreated = Usercreated;
				
			item.Status = Status;
				
	        item.Save(UserName);
	    }
    }
}
