using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SMSFinger.DAL
{
	/// <summary>
	/// Strongly-typed collection for the Messagerecipient class.
	/// </summary>
    [Serializable]
	public partial class MessagerecipientCollection : ActiveList<Messagerecipient, MessagerecipientCollection>
	{	   
		public MessagerecipientCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>MessagerecipientCollection</returns>
		public MessagerecipientCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                Messagerecipient o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the messagerecipient table.
	/// </summary>
	[Serializable]
	public partial class Messagerecipient : ActiveRecord<Messagerecipient>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public Messagerecipient()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public Messagerecipient(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public Messagerecipient(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public Messagerecipient(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("messagerecipient", TableType.Table, DataService.GetInstance("SMSFingerProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarRecipientid = new TableSchema.TableColumn(schema);
				colvarRecipientid.ColumnName = "recipientid";
				colvarRecipientid.DataType = DbType.Int32;
				colvarRecipientid.MaxLength = 0;
				colvarRecipientid.AutoIncrement = false;
				colvarRecipientid.IsNullable = true;
				colvarRecipientid.IsPrimaryKey = false;
				colvarRecipientid.IsForeignKey = false;
				colvarRecipientid.IsReadOnly = false;
				colvarRecipientid.DefaultSetting = @"";
				colvarRecipientid.ForeignKeyTableName = "";
				schema.Columns.Add(colvarRecipientid);
				
				TableSchema.TableColumn colvarRecipientgroupid = new TableSchema.TableColumn(schema);
				colvarRecipientgroupid.ColumnName = "recipientgroupid";
				colvarRecipientgroupid.DataType = DbType.Int32;
				colvarRecipientgroupid.MaxLength = 0;
				colvarRecipientgroupid.AutoIncrement = false;
				colvarRecipientgroupid.IsNullable = true;
				colvarRecipientgroupid.IsPrimaryKey = false;
				colvarRecipientgroupid.IsForeignKey = false;
				colvarRecipientgroupid.IsReadOnly = false;
				colvarRecipientgroupid.DefaultSetting = @"";
				colvarRecipientgroupid.ForeignKeyTableName = "";
				schema.Columns.Add(colvarRecipientgroupid);
				
				TableSchema.TableColumn colvarMessageid = new TableSchema.TableColumn(schema);
				colvarMessageid.ColumnName = "messageid";
				colvarMessageid.DataType = DbType.Int32;
				colvarMessageid.MaxLength = 0;
				colvarMessageid.AutoIncrement = false;
				colvarMessageid.IsNullable = true;
				colvarMessageid.IsPrimaryKey = false;
				colvarMessageid.IsForeignKey = false;
				colvarMessageid.IsReadOnly = false;
				colvarMessageid.DefaultSetting = @"";
				colvarMessageid.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMessageid);
				
				TableSchema.TableColumn colvarReadstatus = new TableSchema.TableColumn(schema);
				colvarReadstatus.ColumnName = "readstatus";
				colvarReadstatus.DataType = DbType.Int32;
				colvarReadstatus.MaxLength = 0;
				colvarReadstatus.AutoIncrement = false;
				colvarReadstatus.IsNullable = true;
				colvarReadstatus.IsPrimaryKey = false;
				colvarReadstatus.IsForeignKey = false;
				colvarReadstatus.IsReadOnly = false;
				colvarReadstatus.DefaultSetting = @"";
				colvarReadstatus.ForeignKeyTableName = "";
				schema.Columns.Add(colvarReadstatus);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["SMSFingerProvider"].AddSchema("messagerecipient",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("Recipientid")]
		[Bindable(true)]
		public int? Recipientid 
		{
			get { return GetColumnValue<int?>(Columns.Recipientid); }
			set { SetColumnValue(Columns.Recipientid, value); }
		}
		  
		[XmlAttribute("Recipientgroupid")]
		[Bindable(true)]
		public int? Recipientgroupid 
		{
			get { return GetColumnValue<int?>(Columns.Recipientgroupid); }
			set { SetColumnValue(Columns.Recipientgroupid, value); }
		}
		  
		[XmlAttribute("Messageid")]
		[Bindable(true)]
		public int? Messageid 
		{
			get { return GetColumnValue<int?>(Columns.Messageid); }
			set { SetColumnValue(Columns.Messageid, value); }
		}
		  
		[XmlAttribute("Readstatus")]
		[Bindable(true)]
		public int? Readstatus 
		{
			get { return GetColumnValue<int?>(Columns.Readstatus); }
			set { SetColumnValue(Columns.Readstatus, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int? varRecipientid,int? varRecipientgroupid,int? varMessageid,int? varReadstatus)
		{
			Messagerecipient item = new Messagerecipient();
			
			item.Recipientid = varRecipientid;
			
			item.Recipientgroupid = varRecipientgroupid;
			
			item.Messageid = varMessageid;
			
			item.Readstatus = varReadstatus;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,int? varRecipientid,int? varRecipientgroupid,int? varMessageid,int? varReadstatus)
		{
			Messagerecipient item = new Messagerecipient();
			
				item.Id = varId;
			
				item.Recipientid = varRecipientid;
			
				item.Recipientgroupid = varRecipientgroupid;
			
				item.Messageid = varMessageid;
			
				item.Readstatus = varReadstatus;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn RecipientidColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn RecipientgroupidColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn MessageidColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn ReadstatusColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string Recipientid = @"recipientid";
			 public static string Recipientgroupid = @"recipientgroupid";
			 public static string Messageid = @"messageid";
			 public static string Readstatus = @"readstatus";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
