using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SMSFinger.DAL
{
    /// <summary>
    /// Controller class for messagerecipient
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class MessagerecipientController
    {
        // Preload our schema..
        Messagerecipient thisSchemaLoad = new Messagerecipient();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public MessagerecipientCollection FetchAll()
        {
            MessagerecipientCollection coll = new MessagerecipientCollection();
            Query qry = new Query(Messagerecipient.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public MessagerecipientCollection FetchByID(object Id)
        {
            MessagerecipientCollection coll = new MessagerecipientCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public MessagerecipientCollection FetchByQuery(Query qry)
        {
            MessagerecipientCollection coll = new MessagerecipientCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (Messagerecipient.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (Messagerecipient.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int? Recipientid,int? Recipientgroupid,int? Messageid,int? Readstatus)
	    {
		    Messagerecipient item = new Messagerecipient();
		    
            item.Recipientid = Recipientid;
            
            item.Recipientgroupid = Recipientgroupid;
            
            item.Messageid = Messageid;
            
            item.Readstatus = Readstatus;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int? Recipientid,int? Recipientgroupid,int? Messageid,int? Readstatus)
	    {
		    Messagerecipient item = new Messagerecipient();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Recipientid = Recipientid;
				
			item.Recipientgroupid = Recipientgroupid;
				
			item.Messageid = Messageid;
				
			item.Readstatus = Readstatus;
				
	        item.Save(UserName);
	    }
    }
}
