using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SMSFinger.DAL
{
    /// <summary>
    /// Controller class for reminderfrequency
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class ReminderfrequencyController
    {
        // Preload our schema..
        Reminderfrequency thisSchemaLoad = new Reminderfrequency();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ReminderfrequencyCollection FetchAll()
        {
            ReminderfrequencyCollection coll = new ReminderfrequencyCollection();
            Query qry = new Query(Reminderfrequency.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ReminderfrequencyCollection FetchByID(object Id)
        {
            ReminderfrequencyCollection coll = new ReminderfrequencyCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public ReminderfrequencyCollection FetchByQuery(Query qry)
        {
            ReminderfrequencyCollection coll = new ReminderfrequencyCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (Reminderfrequency.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (Reminderfrequency.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Title,int? Frequency,int? Status)
	    {
		    Reminderfrequency item = new Reminderfrequency();
		    
            item.Title = Title;
            
            item.Frequency = Frequency;
            
            item.Status = Status;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string Title,int? Frequency,int? Status)
	    {
		    Reminderfrequency item = new Reminderfrequency();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Title = Title;
				
			item.Frequency = Frequency;
				
			item.Status = Status;
				
	        item.Save(UserName);
	    }
    }
}
