using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SMSFinger.DAL
{
	/// <summary>
	/// Strongly-typed collection for the Sentmessage class.
	/// </summary>
    [Serializable]
	public partial class SentmessageCollection : ActiveList<Sentmessage, SentmessageCollection>
	{	   
		public SentmessageCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>SentmessageCollection</returns>
		public SentmessageCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                Sentmessage o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the sentmessages table.
	/// </summary>
	[Serializable]
	public partial class Sentmessage : ActiveRecord<Sentmessage>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public Sentmessage()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public Sentmessage(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public Sentmessage(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public Sentmessage(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("sentmessages", TableType.Table, DataService.GetInstance("SMSFingerProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"";
				//columns
				
				TableSchema.TableColumn colvarMsgid = new TableSchema.TableColumn(schema);
				colvarMsgid.ColumnName = "msgid";
				colvarMsgid.DataType = DbType.Int32;
				colvarMsgid.MaxLength = 0;
				colvarMsgid.AutoIncrement = true;
				colvarMsgid.IsNullable = false;
				colvarMsgid.IsPrimaryKey = true;
				colvarMsgid.IsForeignKey = false;
				colvarMsgid.IsReadOnly = false;
				colvarMsgid.DefaultSetting = @"";
				colvarMsgid.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMsgid);
				
				TableSchema.TableColumn colvarMobileno = new TableSchema.TableColumn(schema);
				colvarMobileno.ColumnName = "mobileno";
				colvarMobileno.DataType = DbType.String;
				colvarMobileno.MaxLength = 15;
				colvarMobileno.AutoIncrement = false;
				colvarMobileno.IsNullable = true;
				colvarMobileno.IsPrimaryKey = false;
				colvarMobileno.IsForeignKey = false;
				colvarMobileno.IsReadOnly = false;
				colvarMobileno.DefaultSetting = @"";
				colvarMobileno.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMobileno);
				
				TableSchema.TableColumn colvarMessagebody = new TableSchema.TableColumn(schema);
				colvarMessagebody.ColumnName = "messagebody";
				colvarMessagebody.DataType = DbType.String;
				colvarMessagebody.MaxLength = 500;
				colvarMessagebody.AutoIncrement = false;
				colvarMessagebody.IsNullable = true;
				colvarMessagebody.IsPrimaryKey = false;
				colvarMessagebody.IsForeignKey = false;
				colvarMessagebody.IsReadOnly = false;
				colvarMessagebody.DefaultSetting = @"";
				colvarMessagebody.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMessagebody);
				
				TableSchema.TableColumn colvarMsgtype = new TableSchema.TableColumn(schema);
				colvarMsgtype.ColumnName = "msgtype";
				colvarMsgtype.DataType = DbType.Int32;
				colvarMsgtype.MaxLength = 0;
				colvarMsgtype.AutoIncrement = false;
				colvarMsgtype.IsNullable = true;
				colvarMsgtype.IsPrimaryKey = false;
				colvarMsgtype.IsForeignKey = false;
				colvarMsgtype.IsReadOnly = false;
				colvarMsgtype.DefaultSetting = @"";
				colvarMsgtype.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMsgtype);
				
				TableSchema.TableColumn colvarDatecreated = new TableSchema.TableColumn(schema);
				colvarDatecreated.ColumnName = "datecreated";
				colvarDatecreated.DataType = DbType.DateTime;
				colvarDatecreated.MaxLength = 0;
				colvarDatecreated.AutoIncrement = false;
				colvarDatecreated.IsNullable = true;
				colvarDatecreated.IsPrimaryKey = false;
				colvarDatecreated.IsForeignKey = false;
				colvarDatecreated.IsReadOnly = false;
				colvarDatecreated.DefaultSetting = @"";
				colvarDatecreated.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDatecreated);
				
				TableSchema.TableColumn colvarUsercreated = new TableSchema.TableColumn(schema);
				colvarUsercreated.ColumnName = "usercreated";
				colvarUsercreated.DataType = DbType.Int32;
				colvarUsercreated.MaxLength = 0;
				colvarUsercreated.AutoIncrement = false;
				colvarUsercreated.IsNullable = true;
				colvarUsercreated.IsPrimaryKey = false;
				colvarUsercreated.IsForeignKey = false;
				colvarUsercreated.IsReadOnly = false;
				colvarUsercreated.DefaultSetting = @"";
				colvarUsercreated.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUsercreated);
				
				TableSchema.TableColumn colvarAcid = new TableSchema.TableColumn(schema);
				colvarAcid.ColumnName = "acid";
				colvarAcid.DataType = DbType.Int32;
				colvarAcid.MaxLength = 0;
				colvarAcid.AutoIncrement = false;
				colvarAcid.IsNullable = true;
				colvarAcid.IsPrimaryKey = false;
				colvarAcid.IsForeignKey = false;
				colvarAcid.IsReadOnly = false;
				colvarAcid.DefaultSetting = @"";
				colvarAcid.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAcid);
				
				TableSchema.TableColumn colvarMsgstatus = new TableSchema.TableColumn(schema);
				colvarMsgstatus.ColumnName = "msgstatus";
				colvarMsgstatus.DataType = DbType.String;
				colvarMsgstatus.MaxLength = 50;
				colvarMsgstatus.AutoIncrement = false;
				colvarMsgstatus.IsNullable = true;
				colvarMsgstatus.IsPrimaryKey = false;
				colvarMsgstatus.IsForeignKey = false;
				colvarMsgstatus.IsReadOnly = false;
				colvarMsgstatus.DefaultSetting = @"";
				colvarMsgstatus.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMsgstatus);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["SMSFingerProvider"].AddSchema("sentmessages",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Msgid")]
		[Bindable(true)]
		public int Msgid 
		{
			get { return GetColumnValue<int>(Columns.Msgid); }
			set { SetColumnValue(Columns.Msgid, value); }
		}
		  
		[XmlAttribute("Mobileno")]
		[Bindable(true)]
		public string Mobileno 
		{
			get { return GetColumnValue<string>(Columns.Mobileno); }
			set { SetColumnValue(Columns.Mobileno, value); }
		}
		  
		[XmlAttribute("Messagebody")]
		[Bindable(true)]
		public string Messagebody 
		{
			get { return GetColumnValue<string>(Columns.Messagebody); }
			set { SetColumnValue(Columns.Messagebody, value); }
		}
		  
		[XmlAttribute("Msgtype")]
		[Bindable(true)]
		public int? Msgtype 
		{
			get { return GetColumnValue<int?>(Columns.Msgtype); }
			set { SetColumnValue(Columns.Msgtype, value); }
		}
		  
		[XmlAttribute("Datecreated")]
		[Bindable(true)]
		public DateTime? Datecreated 
		{
			get { return GetColumnValue<DateTime?>(Columns.Datecreated); }
			set { SetColumnValue(Columns.Datecreated, value); }
		}
		  
		[XmlAttribute("Usercreated")]
		[Bindable(true)]
		public int? Usercreated 
		{
			get { return GetColumnValue<int?>(Columns.Usercreated); }
			set { SetColumnValue(Columns.Usercreated, value); }
		}
		  
		[XmlAttribute("Acid")]
		[Bindable(true)]
		public int? Acid 
		{
			get { return GetColumnValue<int?>(Columns.Acid); }
			set { SetColumnValue(Columns.Acid, value); }
		}
		  
		[XmlAttribute("Msgstatus")]
		[Bindable(true)]
		public string Msgstatus 
		{
			get { return GetColumnValue<string>(Columns.Msgstatus); }
			set { SetColumnValue(Columns.Msgstatus, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varMobileno,string varMessagebody,int? varMsgtype,DateTime? varDatecreated,int? varUsercreated,int? varAcid,string varMsgstatus)
		{
			Sentmessage item = new Sentmessage();
			
			item.Mobileno = varMobileno;
			
			item.Messagebody = varMessagebody;
			
			item.Msgtype = varMsgtype;
			
			item.Datecreated = varDatecreated;
			
			item.Usercreated = varUsercreated;
			
			item.Acid = varAcid;
			
			item.Msgstatus = varMsgstatus;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varMsgid,string varMobileno,string varMessagebody,int? varMsgtype,DateTime? varDatecreated,int? varUsercreated,int? varAcid,string varMsgstatus)
		{
			Sentmessage item = new Sentmessage();
			
				item.Msgid = varMsgid;
			
				item.Mobileno = varMobileno;
			
				item.Messagebody = varMessagebody;
			
				item.Msgtype = varMsgtype;
			
				item.Datecreated = varDatecreated;
			
				item.Usercreated = varUsercreated;
			
				item.Acid = varAcid;
			
				item.Msgstatus = varMsgstatus;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn MsgidColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn MobilenoColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn MessagebodyColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn MsgtypeColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn DatecreatedColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn UsercreatedColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn AcidColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn MsgstatusColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Msgid = @"msgid";
			 public static string Mobileno = @"mobileno";
			 public static string Messagebody = @"messagebody";
			 public static string Msgtype = @"msgtype";
			 public static string Datecreated = @"datecreated";
			 public static string Usercreated = @"usercreated";
			 public static string Acid = @"acid";
			 public static string Msgstatus = @"msgstatus";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
