using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SMSFinger.DAL
{
	/// <summary>
	/// Strongly-typed collection for the User class.
	/// </summary>
    [Serializable]
	public partial class UserCollection : ActiveList<User, UserCollection>
	{	   
		public UserCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>UserCollection</returns>
		public UserCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                User o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the user table.
	/// </summary>
	[Serializable]
	public partial class User : ActiveRecord<User>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public User()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public User(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public User(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public User(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("user", TableType.Table, DataService.GetInstance("SMSFingerProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarAcid = new TableSchema.TableColumn(schema);
				colvarAcid.ColumnName = "acid";
				colvarAcid.DataType = DbType.Int32;
				colvarAcid.MaxLength = 0;
				colvarAcid.AutoIncrement = false;
				colvarAcid.IsNullable = true;
				colvarAcid.IsPrimaryKey = false;
				colvarAcid.IsForeignKey = false;
				colvarAcid.IsReadOnly = false;
				colvarAcid.DefaultSetting = @"";
				colvarAcid.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAcid);
				
				TableSchema.TableColumn colvarFirstname = new TableSchema.TableColumn(schema);
				colvarFirstname.ColumnName = "firstname";
				colvarFirstname.DataType = DbType.String;
				colvarFirstname.MaxLength = 50;
				colvarFirstname.AutoIncrement = false;
				colvarFirstname.IsNullable = true;
				colvarFirstname.IsPrimaryKey = false;
				colvarFirstname.IsForeignKey = false;
				colvarFirstname.IsReadOnly = false;
				colvarFirstname.DefaultSetting = @"";
				colvarFirstname.ForeignKeyTableName = "";
				schema.Columns.Add(colvarFirstname);
				
				TableSchema.TableColumn colvarLastname = new TableSchema.TableColumn(schema);
				colvarLastname.ColumnName = "lastname";
				colvarLastname.DataType = DbType.String;
				colvarLastname.MaxLength = 50;
				colvarLastname.AutoIncrement = false;
				colvarLastname.IsNullable = true;
				colvarLastname.IsPrimaryKey = false;
				colvarLastname.IsForeignKey = false;
				colvarLastname.IsReadOnly = false;
				colvarLastname.DefaultSetting = @"";
				colvarLastname.ForeignKeyTableName = "";
				schema.Columns.Add(colvarLastname);
				
				TableSchema.TableColumn colvarGender = new TableSchema.TableColumn(schema);
				colvarGender.ColumnName = "gender";
				colvarGender.DataType = DbType.String;
				colvarGender.MaxLength = 10;
				colvarGender.AutoIncrement = false;
				colvarGender.IsNullable = true;
				colvarGender.IsPrimaryKey = false;
				colvarGender.IsForeignKey = false;
				colvarGender.IsReadOnly = false;
				colvarGender.DefaultSetting = @"";
				colvarGender.ForeignKeyTableName = "";
				schema.Columns.Add(colvarGender);
				
				TableSchema.TableColumn colvarEmail = new TableSchema.TableColumn(schema);
				colvarEmail.ColumnName = "email";
				colvarEmail.DataType = DbType.String;
				colvarEmail.MaxLength = 50;
				colvarEmail.AutoIncrement = false;
				colvarEmail.IsNullable = true;
				colvarEmail.IsPrimaryKey = false;
				colvarEmail.IsForeignKey = false;
				colvarEmail.IsReadOnly = false;
				colvarEmail.DefaultSetting = @"";
				colvarEmail.ForeignKeyTableName = "";
				schema.Columns.Add(colvarEmail);
				
				TableSchema.TableColumn colvarPassword = new TableSchema.TableColumn(schema);
				colvarPassword.ColumnName = "password";
				colvarPassword.DataType = DbType.String;
				colvarPassword.MaxLength = 100;
				colvarPassword.AutoIncrement = false;
				colvarPassword.IsNullable = true;
				colvarPassword.IsPrimaryKey = false;
				colvarPassword.IsForeignKey = false;
				colvarPassword.IsReadOnly = false;
				colvarPassword.DefaultSetting = @"";
				colvarPassword.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPassword);
				
				TableSchema.TableColumn colvarStatus = new TableSchema.TableColumn(schema);
				colvarStatus.ColumnName = "status";
				colvarStatus.DataType = DbType.Int32;
				colvarStatus.MaxLength = 0;
				colvarStatus.AutoIncrement = false;
				colvarStatus.IsNullable = true;
				colvarStatus.IsPrimaryKey = false;
				colvarStatus.IsForeignKey = false;
				colvarStatus.IsReadOnly = false;
				colvarStatus.DefaultSetting = @"";
				colvarStatus.ForeignKeyTableName = "";
				schema.Columns.Add(colvarStatus);
				
				TableSchema.TableColumn colvarDatecreated = new TableSchema.TableColumn(schema);
				colvarDatecreated.ColumnName = "datecreated";
				colvarDatecreated.DataType = DbType.DateTime;
				colvarDatecreated.MaxLength = 0;
				colvarDatecreated.AutoIncrement = false;
				colvarDatecreated.IsNullable = true;
				colvarDatecreated.IsPrimaryKey = false;
				colvarDatecreated.IsForeignKey = false;
				colvarDatecreated.IsReadOnly = false;
				colvarDatecreated.DefaultSetting = @"";
				colvarDatecreated.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDatecreated);
				
				TableSchema.TableColumn colvarUsercreated = new TableSchema.TableColumn(schema);
				colvarUsercreated.ColumnName = "usercreated";
				colvarUsercreated.DataType = DbType.Int32;
				colvarUsercreated.MaxLength = 0;
				colvarUsercreated.AutoIncrement = false;
				colvarUsercreated.IsNullable = true;
				colvarUsercreated.IsPrimaryKey = false;
				colvarUsercreated.IsForeignKey = false;
				colvarUsercreated.IsReadOnly = false;
				colvarUsercreated.DefaultSetting = @"";
				colvarUsercreated.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUsercreated);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["SMSFingerProvider"].AddSchema("user",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("Acid")]
		[Bindable(true)]
		public int? Acid 
		{
			get { return GetColumnValue<int?>(Columns.Acid); }
			set { SetColumnValue(Columns.Acid, value); }
		}
		  
		[XmlAttribute("Firstname")]
		[Bindable(true)]
		public string Firstname 
		{
			get { return GetColumnValue<string>(Columns.Firstname); }
			set { SetColumnValue(Columns.Firstname, value); }
		}
		  
		[XmlAttribute("Lastname")]
		[Bindable(true)]
		public string Lastname 
		{
			get { return GetColumnValue<string>(Columns.Lastname); }
			set { SetColumnValue(Columns.Lastname, value); }
		}
		  
		[XmlAttribute("Gender")]
		[Bindable(true)]
		public string Gender 
		{
			get { return GetColumnValue<string>(Columns.Gender); }
			set { SetColumnValue(Columns.Gender, value); }
		}
		  
		[XmlAttribute("Email")]
		[Bindable(true)]
		public string Email 
		{
			get { return GetColumnValue<string>(Columns.Email); }
			set { SetColumnValue(Columns.Email, value); }
		}
		  
		[XmlAttribute("Password")]
		[Bindable(true)]
		public string Password 
		{
			get { return GetColumnValue<string>(Columns.Password); }
			set { SetColumnValue(Columns.Password, value); }
		}
		  
		[XmlAttribute("Status")]
		[Bindable(true)]
		public int? Status 
		{
			get { return GetColumnValue<int?>(Columns.Status); }
			set { SetColumnValue(Columns.Status, value); }
		}
		  
		[XmlAttribute("Datecreated")]
		[Bindable(true)]
		public DateTime? Datecreated 
		{
			get { return GetColumnValue<DateTime?>(Columns.Datecreated); }
			set { SetColumnValue(Columns.Datecreated, value); }
		}
		  
		[XmlAttribute("Usercreated")]
		[Bindable(true)]
		public int? Usercreated 
		{
			get { return GetColumnValue<int?>(Columns.Usercreated); }
			set { SetColumnValue(Columns.Usercreated, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int? varAcid,string varFirstname,string varLastname,string varGender,string varEmail,string varPassword,int? varStatus,DateTime? varDatecreated,int? varUsercreated)
		{
			User item = new User();
			
			item.Acid = varAcid;
			
			item.Firstname = varFirstname;
			
			item.Lastname = varLastname;
			
			item.Gender = varGender;
			
			item.Email = varEmail;
			
			item.Password = varPassword;
			
			item.Status = varStatus;
			
			item.Datecreated = varDatecreated;
			
			item.Usercreated = varUsercreated;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,int? varAcid,string varFirstname,string varLastname,string varGender,string varEmail,string varPassword,int? varStatus,DateTime? varDatecreated,int? varUsercreated)
		{
			User item = new User();
			
				item.Id = varId;
			
				item.Acid = varAcid;
			
				item.Firstname = varFirstname;
			
				item.Lastname = varLastname;
			
				item.Gender = varGender;
			
				item.Email = varEmail;
			
				item.Password = varPassword;
			
				item.Status = varStatus;
			
				item.Datecreated = varDatecreated;
			
				item.Usercreated = varUsercreated;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn AcidColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn FirstnameColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn LastnameColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn GenderColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn EmailColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn PasswordColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn StatusColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn DatecreatedColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn UsercreatedColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string Acid = @"acid";
			 public static string Firstname = @"firstname";
			 public static string Lastname = @"lastname";
			 public static string Gender = @"gender";
			 public static string Email = @"email";
			 public static string Password = @"password";
			 public static string Status = @"status";
			 public static string Datecreated = @"datecreated";
			 public static string Usercreated = @"usercreated";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
