//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsFinger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accout
    {
        public int id { get; set; }
        public string acname { get; set; }
        public string mpoc { get; set; }
        public string mobileno { get; set; }
        public string email { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public string remarks { get; set; }
    }
}
