//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsFinger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string groupname { get; set; }
        public Nullable<int> acid { get; set; }
        public Nullable<int> usercreated { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<int> status { get; set; }
    }
}
