//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsFinger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int id { get; set; }
        public string subject { get; set; }
        public Nullable<int> creatorid { get; set; }
        public byte[] messagebody { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<int> parentmessageid { get; set; }
        public Nullable<System.DateTime> expirydate { get; set; }
        public Nullable<int> isreminder { get; set; }
        public Nullable<System.DateTime> nextreminddate { get; set; }
        public Nullable<int> reminderfrequencyid { get; set; }
    }
}
