//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsFinger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reminderfrequency
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> frequency { get; set; }
        public Nullable<int> status { get; set; }
    }
}
