//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsFinger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class role_module_permisions
    {
        public long urmpid { get; set; }
        public long roleid { get; set; }
        public int mid { get; set; }
        public Nullable<bool> pc { get; set; }
        public Nullable<bool> pr { get; set; }
        public Nullable<bool> pu { get; set; }
        public Nullable<bool> pd { get; set; }
    }
}
