//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsFinger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sentmessage
    {
        public int msgid { get; set; }
        public string mobileno { get; set; }
        public string messagebody { get; set; }
        public Nullable<int> msgtype { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<int> usercreated { get; set; }
        public Nullable<int> acid { get; set; }
        public string msgstatus { get; set; }
    }
}
