//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsFinger.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class smsfingerDB : DbContext
    {
        public smsfingerDB()
            : base("name=smsfingerDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<accout> accouts { get; set; }
        public DbSet<contact> contacts { get; set; }
        public DbSet<group> groups { get; set; }
        public DbSet<message> messages { get; set; }
        public DbSet<messagerecipient> messagerecipients { get; set; }
        public DbSet<reminderfrequency> reminderfrequencies { get; set; }
        public DbSet<sentmessage> sentmessages { get; set; }
        public DbSet<user> users { get; set; }
    }
}
